name: Jekyll Themes
url: https://github.com/jknappe/zw-ireland
description: Insert tagline here

permalink: /themes/:title/

gems: [jekyll-paginate]

highlighter: rouge
paginate: 20

markdown: rdiscount
rdiscount:
    extensions: ['smart']

exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile', 'vendor']
